-- Learn Content System Migration for Testograph
-- AI-powered cluster & pillar content generation
-- Created: 2025-01-18

-- Create blog_posts table for learn guides
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL, -- HTML content generated by AI
  excerpt text,

  -- Categorization
  category text NOT NULL DEFAULT 'learn-guide', -- 'learn-guide' | 'blog-post' | 'news'
  guide_type text CHECK (guide_type IN ('cluster', 'pillar')), -- For learn-guide category only
  guide_category text, -- 'testosterone', 'potency', 'fitness', 'nutrition', 'supplements', 'lifestyle'

  -- Cluster/Pillar relationship
  suggested_pillars text[], -- For cluster guides: array of suggested pillar titles
  parent_cluster_slug text, -- For pillar guides: slug of parent cluster

  -- SEO & Metadata
  meta_title text NOT NULL,
  meta_description text NOT NULL,
  featured_image_url text, -- Hero image URL (16:9 aspect ratio)

  -- Author & Publishing
  author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_at timestamptz,
  is_published boolean DEFAULT false,

  -- Timestamps
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON public.blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_guide_category ON public.blog_posts(guide_category) WHERE category = 'learn-guide';
CREATE INDEX IF NOT EXISTS idx_blog_posts_guide_type ON public.blog_posts(guide_type) WHERE category = 'learn-guide';
CREATE INDEX IF NOT EXISTS idx_blog_posts_parent_cluster ON public.blog_posts(parent_cluster_slug) WHERE guide_type = 'pillar';
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON public.blog_posts(is_published, published_at);

-- Enable Row Level Security (RLS)
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public can read published guides
CREATE POLICY "Public can read published guides"
  ON public.blog_posts
  FOR SELECT
  USING (is_published = true);

-- RLS Policy: Admins can do everything
CREATE POLICY "Admins can manage all guides"
  ON public.blog_posts
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.id = auth.uid()
    )
  );

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_blog_posts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER update_blog_posts_updated_at_trigger
  BEFORE UPDATE ON public.blog_posts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_blog_posts_updated_at();

-- Add comment to table
COMMENT ON TABLE public.blog_posts IS 'Learn guides and blog posts. Learn guides use cluster-pillar architecture for SEO content.';
COMMENT ON COLUMN public.blog_posts.category IS 'Content type: learn-guide (SEO content), blog-post, news';
COMMENT ON COLUMN public.blog_posts.guide_type IS 'For learn-guide category: cluster (hub page) or pillar (spoke page)';
COMMENT ON COLUMN public.blog_posts.guide_category IS 'For Testograph: testosterone, potency, fitness, nutrition, supplements, lifestyle';
COMMENT ON COLUMN public.blog_posts.suggested_pillars IS 'For cluster guides: AI-generated array of 8-12 specific pillar topic suggestions';
COMMENT ON COLUMN public.blog_posts.parent_cluster_slug IS 'For pillar guides: slug of parent cluster guide for internal linking';
